# Generated by Django 5.0 on 2023-12-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус заказа'),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
